remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
title:  'Relationship Between Recipe Ratings and Number of Steps'
description: "Analysis done using Python Pandas for DSC80 FA'23 at UCSD."
